version: 2
updates:
  - package-ecosystem: npm
    directory: "/src/app"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      npm-major:
        applies-to: version-updates
        update-types:
          - major
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: "/src/api"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      nuget-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      nuget-major:
        applies-to: version-updates
        update-types:
          - major
        patterns:
          - "*"
